import {
  ANTENNA_BASE_ASSET_ID,
  ANTENNA_STEM_ASSET_ID,
  BODY_HIGHLIGHT_ASSET_ID,
  BODY_SHELL_ASSET_ID,
  FACE_BLUSH_ASSET_ID,
  FACE_ERROR_EYES_ASSET_ID,
  FACE_ERROR_MOUTH_ASSET_ID,
  FACE_EYES_ASSET_ID,
  FACE_FRAME_ASSET_ID,
  FACE_GLASS_ASSET_ID,
  FACE_MOUTH_ASSET_ID,
  FACE_REFLECTION_ASSET_ID,
  FACE_THINKING_EYES_ASSET_ID,
  LEFT_ARM_ASSET_ID,
  RIGHT_ARM_ASSET_ID,
} from "./geometry";
import {
  cloneSceneDefinition,
  SCENE_ORIGIN,
  SCENE_PERSPECTIVE_PX,
  type SceneDefinition,
} from "./scene";

export const MASCOT_SCENE_V1_ID = "mascot-scene-v1" as const;

const BODY_SHELL_Z = -5;
const BODY_SHELL_DEPTH_SCALE = (SCENE_PERSPECTIVE_PX - BODY_SHELL_Z) / SCENE_PERSPECTIVE_PX;

const MASCOT_SCENE_V1: SceneDefinition = {
  scenePivot: { x: SCENE_ORIGIN.x, y: SCENE_ORIGIN.y, z: 0 },
  layers: [
    {
      assetID: LEFT_ARM_ASSET_ID,
      id: "left-arm-plane",
      label: "左手臂",
      parentID: null,
      position: { x: -45, y: 23.5, z: 0 },
      size: { width: 20, height: 29, depth: 0 },
      pivot: { x: -40, y: 11, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      idleMotion: {
        durationMs: 3400,
        delayMs: 0,
        rest: { translateX: 0, translateY: 0, rotateZ: 0 },
        peak: { translateX: 0, translateY: -3, rotateZ: 0 },
      },
      debugColor: "#94a3b8",
    },
    {
      assetID: RIGHT_ARM_ASSET_ID,
      id: "right-arm-plane",
      label: "右手臂",
      parentID: null,
      position: { x: 45, y: 23.5, z: 0 },
      size: { width: 20, height: 29, depth: 0 },
      pivot: { x: 40, y: 11, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      idleMotion: {
        durationMs: 3400,
        delayMs: 120,
        rest: { translateX: 0, translateY: 0, rotateZ: 0 },
        peak: { translateX: 0, translateY: -2.7, rotateZ: 0 },
      },
      debugColor: "#94a3b8",
    },
    {
      assetID: BODY_SHELL_ASSET_ID,
      id: "rear-plane",
      label: "主体后壳",
      parentID: null,
      position: { x: 0, y: -5, z: BODY_SHELL_Z },
      size: { width: 92 * BODY_SHELL_DEPTH_SCALE, height: 80 * BODY_SHELL_DEPTH_SCALE, depth: 0 },
      pivot: { x: 0, y: 0, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      debugColor: "#6366f1",
    },
    {
      assetID: BODY_HIGHLIGHT_ASSET_ID,
      id: "middle-plane",
      label: "中层高光",
      parentID: null,
      position: { x: 0, y: -5, z: 0 },
      size: { width: 90, height: 78, depth: 0 },
      pivot: { x: 0, y: 0, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      debugColor: "#10b981",
    },
    {
      assetID: ANTENNA_STEM_ASSET_ID,
      id: "antenna-stem-plane",
      label: "天线杆",
      parentID: null,
      position: { x: 0, y: -52.5, z: -0.5 },
      size: { width: 24, height: 26, depth: 0 },
      pivot: { x: 0, y: 11, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      idleMotion: {
        durationMs: 3600,
        delayMs: 180,
        rest: { translateX: 0, translateY: 0, rotateZ: -3 },
        peak: { translateX: 0, translateY: 0, rotateZ: 4 },
      },
      debugColor: "#818cf8",
    },
    {
      assetID: ANTENNA_BASE_ASSET_ID,
      id: "antenna-base-plane",
      label: "天线底座",
      parentID: null,
      position: { x: 0, y: -42.5, z: 0.5 },
      size: { width: 20, height: 10, depth: 0 },
      pivot: { x: 0, y: 0, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      debugColor: "#a5b4fc",
    },
    {
      assetID: FACE_FRAME_ASSET_ID,
      id: "front-plane",
      label: "前部面框",
      parentID: null,
      position: { x: 0, y: -0.5, z: 4 },
      size: { width: 72, height: 49, depth: 0 },
      pivot: { x: 0, y: 0, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      poseResponse: { yawTranslateX: 4, pitchTranslateY: -2, yawScaleX: 0.04 },
      debugColor: "#f97316",
    },
    {
      assetID: FACE_GLASS_ASSET_ID,
      id: "face-glass-plane",
      label: "内面罩玻璃",
      parentID: "front-plane",
      position: { x: 0, y: 0, z: -3 },
      size: { width: 72, height: 49, depth: 0 },
      pivot: { x: 0, y: 0, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      debugColor: "#84cc16",
    },
    {
      assetID: FACE_EYES_ASSET_ID,
      id: "face-eyes-plane",
      label: "眼睛",
      parentID: "face-glass-plane",
      position: { x: 0, y: 0, z: 0.5 },
      size: { width: 72, height: 49, depth: 0 },
      pivot: { x: 0, y: -7.5, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      assetAnimation: { preset: "blink", durationMs: 6000, delayMs: 0 },
      debugColor: "#334155",
      moods: ["idle"],
    },
    {
      assetID: FACE_THINKING_EYES_ASSET_ID,
      id: "face-thinking-eyes-plane",
      label: "思考眼睛",
      parentID: "face-glass-plane",
      position: { x: 0, y: 0, z: 1.1 },
      size: { width: 72, height: 49, depth: 0 },
      pivot: { x: 0, y: 0, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      debugColor: "#6366f1",
      moods: ["thinking"],
    },
    {
      assetID: FACE_MOUTH_ASSET_ID,
      id: "face-mouth-plane",
      label: "嘴部",
      parentID: "face-glass-plane",
      position: { x: 0, y: 0, z: 0.5 },
      size: { width: 72, height: 49, depth: 0 },
      pivot: { x: 0, y: 12, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      assetAnimation: { preset: "mouth-idle", durationMs: 7200, delayMs: 1100 },
      debugColor: "#64748b",
      moods: ["idle", "thinking"],
    },
    {
      assetID: FACE_BLUSH_ASSET_ID,
      id: "face-blush-plane",
      label: "腮红",
      parentID: "face-glass-plane",
      position: { x: 0, y: 0, z: 0.5 },
      size: { width: 72, height: 49, depth: 0 },
      pivot: { x: 0, y: 0, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      debugColor: "#fb7185",
      moods: ["idle", "thinking"],
    },
    {
      assetID: FACE_ERROR_EYES_ASSET_ID,
      id: "face-error-eyes-plane",
      label: "错误眼睛",
      parentID: "face-glass-plane",
      position: { x: 0, y: 0, z: 0.5 },
      size: { width: 72, height: 49, depth: 0 },
      pivot: { x: 0, y: 0, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      debugColor: "#dc2626",
      moods: ["error"],
    },
    {
      assetID: FACE_ERROR_MOUTH_ASSET_ID,
      id: "face-error-mouth-plane",
      label: "错误嘴型",
      parentID: "face-glass-plane",
      position: { x: 0, y: 0, z: 0.5 },
      size: { width: 72, height: 49, depth: 0 },
      pivot: { x: 0, y: 0, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      debugColor: "#ef4444",
      moods: ["error"],
    },
    {
      assetID: FACE_REFLECTION_ASSET_ID,
      id: "face-reflection-plane",
      label: "面罩反光",
      parentID: "face-glass-plane",
      position: { x: 0, y: 0, z: 1 },
      size: { width: 72, height: 49, depth: 0 },
      pivot: { x: 0, y: 0, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      debugColor: "#e2e8f0",
    },
  ],
};

export function createMascotSceneV1(): SceneDefinition {
  return cloneSceneDefinition(MASCOT_SCENE_V1);
}
