package tool

import "runtime"

func commandRunDescription() string {
	if runtime.GOOS == "windows" {
		return "Run one PowerShell 7 x64 command in an authorized project directory, without a project sandbox. Set execution=host and include a concrete host_access_reason; Ask and Auto require approval for every invocation. Full Access retains its explicit host permissions. PowerShell 7 (pwsh.exe) must be installed; no fallback to Windows PowerShell 5.1, Git Bash or WSL. Use PowerShell syntax, $env:NAME for environment variables, and & before a quoted executable path. Do not wrap commands in another shell. User profiles are not loaded. Use background=true and builtin_command_session for managed processes; shell background operators and tty are unavailable. Output is UTF-8. Very long commands must be saved as project scripts and invoked by path. Use structured file/Git tools where possible. Never change the shell or permissions to evade a refusal."
	}
	return "Run one fixed-shell command in an authorized project directory. Commands use the project sandbox by default, including after a risk approval. Set execution=host only when the exact invocation genuinely needs host services or credentials; include a concrete host_access_reason and expect a separate approval in Ask or Auto. For another local directory, request that directory instead of using host execution. Auto permits code within the authorized sandbox; loops, variables, functions and opaque scripts do not need approval solely for dynamic syntax. Explicit risks and permission extensions still require review. This is not a read-only or no-side-effects guarantee. The command may use pipelines, redirects, heredocs, and compound expressions. Use $TMPDIR instead of shared /tmp for temporary files. Python packages needed only by sandboxed commands can be installed with python3 -m pip install --user; Pudding redirects that user base into stable project state and supplies the system CA bundle. Do not disable TLS verification. Foreground commands return bounded output and verification diagnostics. Set background=true for a persistent session and receive a process_id; set tty=true only for an interactive CLI or REPL. Manage background sessions with builtin_command_session; action=list finds this session's managed processes. Commands can read and write the current session artifact directory returned by builtin_attachment_export(scope=temp)."
}
